name: release

on:
  workflow_dispatch:
    inputs:
      build:
        description: "Optional post-release build number (e.g. 1 -> .post1)"
        required: false
        type: string
  schedule:
    - cron: "0 0 * * 0"
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  prep:
    name: Prepare version bump
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    outputs:
      version: ${{ steps.buildpkg.outputs.version }}
      changed: ${{ steps.buildpkg.outputs.changed }}
      tag_exists: ${{ steps.tagcheck.outputs.exists }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: conda-incubator/setup-miniconda@v3
        with:
          miniforge-version: "latest"
          environment-file: conda/env.yaml
          channels: conda-forge,nodefaults
          activate-environment: mermaidascii
          auto-update-conda: true
          conda-solver: libmamba
          python-version: "3.11"

      - name: Build package (re-bundle & bump local pyproject if upstream changed)
        id: buildpkg
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PYPI_TOKEN: ${{ secrets.PYPI_TOKEN }}
          BUILD_NUMBER: ${{ inputs.build }}
        run: |
          set -euo pipefail
          bash ./scripts/binary.sh --bump
          poetry build
          VER="$(python scripts/get_version.py)"
          echo "version=$VER" >> "$GITHUB_OUTPUT"
          if git diff --quiet -- pyproject.toml; then
            echo "changed=false" >> "$GITHUB_OUTPUT"
          else
            echo "changed=true" >> "$GITHUB_OUTPUT"
          fi

      - name: Check tag existence
        id: tagcheck
        run: |
          if git rev-parse -q --verify "refs/tags/${{ steps.buildpkg.outputs.version }}"; then
            echo "exists=true" >> "$GITHUB_OUTPUT"
          else
            echo "exists=false" >> "$GITHUB_OUTPUT"
          fi

      - name: Commit changes (tag)
        if: ${{ (github.event_name == 'workflow_dispatch' || github.event_name == 'schedule') && steps.buildpkg.outputs.changed == 'true' && steps.tagcheck.outputs.exists != 'true' }}
        uses: EndBug/add-and-commit@v9
        with:
          author_name: Ivan Ogasawara
          author_email: ivan.ogasawara@gmail.com
          message: "Bump mermaid-ascii to ${{ steps.buildpkg.outputs.version }}"
          add: "pyproject.toml"
          tag: "${{ steps.buildpkg.outputs.version }}"

      - name: Nothing to release (prep)
        if: ${{ (github.event_name == 'workflow_dispatch' || github.event_name == 'schedule') && (steps.buildpkg.outputs.changed != 'true' || steps.tagcheck.outputs.exists == 'true') }}
        run: echo "Up-to-date or tag exists. Skipping."

      - name: New release version
        run: |
          echo "Effective version: ${{ steps.buildpkg.outputs.version }}" >> $GITHUB_STEP_SUMMARY

  build-wheels:
    name: Build wheels
    needs: prep
    if: ${{ needs.prep.outputs.changed == 'true' && needs.prep.outputs.tag_exists != 'true' }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        py: ["3.9", "3.10", "3.11", "3.12", "3.13"]

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Linux/macOS: conda with matrix Python (keeps your flow)
      - name: Setup Conda (Unix)
        if: matrix.os != 'windows-latest'
        uses: conda-incubator/setup-miniconda@v3
        with:
          miniforge-version: "latest"
          environment-file: conda/env.yaml
          channels: conda-forge,nodefaults
          activate-environment: mermaidascii
          auto-update-conda: true
          conda-solver: libmamba
          python-version: ${{ matrix.py }}

      - name: Build upstream binary (Unix)
        if: matrix.os != 'windows-latest'
        shell: bash -l {0}
        run: |
          set -euo pipefail
          bash ./scripts/binary.sh
          poetry build -f wheel
          ls -l dist

      # Windows: setup-go + setup-python (matrix), PowerShell builder
      - name: Setup Go (Windows)
        if: matrix.os == 'windows-latest'
        uses: actions/setup-go@v5
        with:
          go-version: "1.22.x"

      - name: Setup Python (Windows)
        if: matrix.os == 'windows-latest'
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.py }}

      - name: Install Poetry (Windows)
        if: matrix.os == 'windows-latest'
        shell: pwsh
        run: |
          python -m pip install -U pip
          python -m pip install poetry

      - name: Build upstream binary (Windows)
        if: matrix.os == 'windows-latest'
        shell: pwsh
        run: ./scripts/binary.ps1

      - name: Build wheel (Windows)
        if: matrix.os == 'windows-latest'
        shell: pwsh
        run: |
          poetry build -f wheel
          Get-ChildItem dist

      # Upload per (os, py)
      - uses: actions/upload-artifact@v4
        with:
          name: wheels-${{ matrix.os }}-py${{ matrix.py }}
          path: dist/*.whl
          if-no-files-found: error

  publish:
    name: Publish to PyPI
    needs: [prep, build-wheels]
    if: ${{ (github.event_name == 'workflow_dispatch' || github.event_name == 'schedule') && needs.prep.outputs.changed == 'true' && needs.prep.outputs.tag_exists != 'true' }}
    runs-on: ubuntu-latest
    steps:
      - name: Download all wheels
        uses: actions/download-artifact@v4
        with:
          pattern: wheels-*
          path: dist
          merge-multiple: true

      - name: Publish (PyPI)
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_TOKEN }}
          packages-dir: dist
          skip-existing: true

  create-release:
    name: Create GitHub Release
    needs: [prep, publish]
    if: ${{ (github.event_name == 'workflow_dispatch' || github.event_name == 'schedule') && needs.prep.outputs.changed == 'true' && needs.prep.outputs.tag_exists != 'true' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/create-release@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ needs.prep.outputs.version }}
          release_name: Release ${{ needs.prep.outputs.version }}
          body: Update mermaid-ascii to ${{ needs.prep.outputs.version }}
          draft: false
          prerelease: false
